/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Species = IDL.Variant({
  'other' : IDL.Null,
  'feline' : IDL.Null,
  'canine' : IDL.Null,
});
export const Sex = IDL.Variant({
  'female' : IDL.Null,
  'male' : IDL.Null,
  'femaleSpayed' : IDL.Null,
  'maleNeutered' : IDL.Null,
});
export const Task = IDL.Record({
  'histo' : IDL.Bool,
  'labs' : IDL.Bool,
  'culture' : IDL.Bool,
  'pDVMNotified' : IDL.Bool,
  'dailySummary' : IDL.Bool,
  'surgeryReport' : IDL.Bool,
  'imaging' : IDL.Bool,
  'dischargeNotes' : IDL.Bool,
});
export const Appointment = IDL.Record({
  'mrn' : IDL.Text,
  'sex' : Sex,
  'tasks' : Task,
  'ownerName' : IDL.Text,
  'arrivalDate' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'patientName' : IDL.Text,
  'breed' : IDL.Text,
  'caseId' : IDL.Opt(IDL.Nat),
  'species' : Species,
  'appointmentId' : IDL.Nat,
  'reason' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Case = IDL.Record({
  'mrn' : IDL.Text,
  'sex' : Sex,
  'tasks' : Task,
  'arrivalDate' : IDL.Text,
  'presentingComplaint' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'petName' : IDL.Text,
  'appointments' : IDL.Vec(IDL.Nat),
  'notes' : IDL.Text,
  'ownerLastName' : IDL.Text,
  'breed' : IDL.Text,
  'caseId' : IDL.Nat,
  'species' : Species,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAppointment' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Species,
        Sex,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Task,
      ],
      [],
      [],
    ),
  'createCase' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Species,
        IDL.Text,
        Sex,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Task,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteAppointment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteCase' : IDL.Func([IDL.Nat], [], []),
  'getAppointmentById' : IDL.Func([IDL.Nat], [Appointment], ['query']),
  'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAppointmentsByMRN' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getAppointmentsByPatientName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaseById' : IDL.Func([IDL.Nat], [Case], ['query']),
  'getCaseByMRN' : IDL.Func([IDL.Text], [Case], ['query']),
  'getCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
  'getTasksForAppointment' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getTasksForCase' : IDL.Func([IDL.Nat], [Task], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleAppointmentTaskComplete' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'toggleTaskComplete' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'updateAppointment' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Species,
        Sex,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Task,
      ],
      [],
      [],
    ),
  'updateCase' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Species,
        IDL.Text,
        Sex,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Task,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Species = IDL.Variant({
    'other' : IDL.Null,
    'feline' : IDL.Null,
    'canine' : IDL.Null,
  });
  const Sex = IDL.Variant({
    'female' : IDL.Null,
    'male' : IDL.Null,
    'femaleSpayed' : IDL.Null,
    'maleNeutered' : IDL.Null,
  });
  const Task = IDL.Record({
    'histo' : IDL.Bool,
    'labs' : IDL.Bool,
    'culture' : IDL.Bool,
    'pDVMNotified' : IDL.Bool,
    'dailySummary' : IDL.Bool,
    'surgeryReport' : IDL.Bool,
    'imaging' : IDL.Bool,
    'dischargeNotes' : IDL.Bool,
  });
  const Appointment = IDL.Record({
    'mrn' : IDL.Text,
    'sex' : Sex,
    'tasks' : Task,
    'ownerName' : IDL.Text,
    'arrivalDate' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'patientName' : IDL.Text,
    'breed' : IDL.Text,
    'caseId' : IDL.Opt(IDL.Nat),
    'species' : Species,
    'appointmentId' : IDL.Nat,
    'reason' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Case = IDL.Record({
    'mrn' : IDL.Text,
    'sex' : Sex,
    'tasks' : Task,
    'arrivalDate' : IDL.Text,
    'presentingComplaint' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'petName' : IDL.Text,
    'appointments' : IDL.Vec(IDL.Nat),
    'notes' : IDL.Text,
    'ownerLastName' : IDL.Text,
    'breed' : IDL.Text,
    'caseId' : IDL.Nat,
    'species' : Species,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAppointment' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Species,
          Sex,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Task,
        ],
        [],
        [],
      ),
    'createCase' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Species,
          IDL.Text,
          Sex,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Task,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteAppointment' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteCase' : IDL.Func([IDL.Nat], [], []),
    'getAppointmentById' : IDL.Func([IDL.Nat], [Appointment], ['query']),
    'getAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAppointmentsByMRN' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getAppointmentsByPatientName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaseById' : IDL.Func([IDL.Nat], [Case], ['query']),
    'getCaseByMRN' : IDL.Func([IDL.Text], [Case], ['query']),
    'getCases' : IDL.Func([], [IDL.Vec(Case)], ['query']),
    'getTasksForAppointment' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getTasksForCase' : IDL.Func([IDL.Nat], [Task], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleAppointmentTaskComplete' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'toggleTaskComplete' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'updateAppointment' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Species,
          Sex,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Task,
        ],
        [],
        [],
      ),
    'updateCase' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Species,
          IDL.Text,
          Sex,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Task,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };