/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Case {
  'mrn' : string,
  'sex' : Sex,
  'tasks' : Task,
  'arrivalDate' : string,
  'presentingComplaint' : string,
  'dateOfBirth' : string,
  'petName' : string,
  'notes' : string,
  'ownerLastName' : string,
  'breed' : string,
  'caseId' : bigint,
  'species' : Species,
}
export type Sex = { 'female' : null } |
  { 'male' : null } |
  { 'femaleSpayed' : null } |
  { 'maleNeutered' : null };
export type Species = { 'other' : null } |
  { 'feline' : null } |
  { 'canine' : null };
export interface Task {
  'histo' : boolean,
  'labs' : boolean,
  'culture' : boolean,
  'pDVMNotified' : boolean,
  'dailySummary' : boolean,
  'surgeryReport' : boolean,
  'imaging' : boolean,
  'dischargeNotes' : boolean,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCase' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Species,
      string,
      Sex,
      string,
      string,
      string,
      Task,
    ],
    bigint
  >,
  'deleteCase' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaseById' : ActorMethod<[bigint], Case>,
  'getCaseByMRN' : ActorMethod<[string], Case>,
  'getCases' : ActorMethod<[], Array<Case>>,
  'getTasksForCase' : ActorMethod<[bigint], Task>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleTaskComplete' : ActorMethod<[bigint, string, boolean], undefined>,
  'updateCase' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      Species,
      string,
      Sex,
      string,
      string,
      string,
      Task,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];