/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    histo: boolean;
    labs: boolean;
    culture: boolean;
    pDVMNotified: boolean;
    dailySummary: boolean;
    surgeryReport: boolean;
    imaging: boolean;
    dischargeNotes: boolean;
}
export interface Appointment {
    mrn: string;
    sex: Sex;
    tasks: Task;
    ownerName: string;
    arrivalDate: string;
    dateOfBirth: string;
    patientName: string;
    breed: string;
    caseId?: bigint;
    species: Species;
    appointmentId: bigint;
    reason: string;
}
export interface UserProfile {
    name: string;
}
export interface Case {
    mrn: string;
    sex: Sex;
    tasks: Task;
    arrivalDate: string;
    presentingComplaint: string;
    dateOfBirth: string;
    petName: string;
    appointments: Array<bigint>;
    notes: string;
    ownerLastName: string;
    breed: string;
    caseId: bigint;
    species: Species;
}
export enum Sex {
    female = "female",
    male = "male",
    femaleSpayed = "femaleSpayed",
    maleNeutered = "maleNeutered"
}
export enum Species {
    other = "other",
    feline = "feline",
    canine = "canine"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAppointment(patientName: string, ownerName: string, species: Species, sex: Sex, breed: string, mrn: string, arrivalDate: string, reason: string, dateOfBirth: string, tasks: Task): Promise<void>;
    createCase(mrn: string, arrivalDate: string, petName: string, ownerLastName: string, species: Species, breed: string, sex: Sex, dateOfBirth: string, presentingComplaint: string, notes: string, tasks: Task): Promise<bigint>;
    deleteAppointment(appointmentId: bigint): Promise<boolean>;
    deleteCase(caseId: bigint): Promise<void>;
    getAppointmentById(appointmentId: bigint): Promise<Appointment>;
    getAppointments(): Promise<Array<Appointment>>;
    getAppointmentsByMRN(mrn: string): Promise<Array<Appointment>>;
    getAppointmentsByPatientName(patientName: string): Promise<Array<Appointment>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCaseById(caseId: bigint): Promise<Case>;
    getCaseByMRN(mrn: string): Promise<Case>;
    getCases(): Promise<Array<Case>>;
    getTasksForAppointment(appointmentId: bigint): Promise<Task>;
    getTasksForCase(caseId: bigint): Promise<Task>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleAppointmentTaskComplete(appointmentId: bigint, taskName: string, isCompleted: boolean): Promise<void>;
    toggleTaskComplete(caseId: bigint, taskName: string, isCompleted: boolean): Promise<void>;
    updateAppointment(appointmentId: bigint, patientName: string, ownerName: string, species: Species, sex: Sex, breed: string, mrn: string, arrivalDate: string, reason: string, dateOfBirth: string, tasks: Task): Promise<void>;
    updateCase(caseId: bigint, mrn: string, arrivalDate: string, petName: string, ownerLastName: string, species: Species, breed: string, sex: Sex, dateOfBirth: string, presentingComplaint: string, notes: string, tasks: Task): Promise<void>;
}
import type { Appointment as _Appointment, Case as _Case, Sex as _Sex, Species as _Species, Task as _Task, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAppointment(arg0: string, arg1: string, arg2: Species, arg3: Sex, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(arg0, arg1, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg2), to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(arg0, arg1, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg2), to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async createCase(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Species, arg5: string, arg6: Sex, arg7: string, arg8: string, arg9: string, arg10: Task): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCase(arg0, arg1, arg2, arg3, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCase(arg0, arg1, arg2, arg3, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async deleteAppointment(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAppointment(arg0);
            return result;
        }
    }
    async deleteCase(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCase(arg0);
            return result;
        }
    }
    async getAppointmentById(arg0: bigint): Promise<Appointment> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentById(arg0);
                return from_candid_Appointment_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentById(arg0);
            return from_candid_Appointment_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointments();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointments();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointmentsByMRN(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByMRN(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByMRN(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAppointmentsByPatientName(arg0: string): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppointmentsByPatientName(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppointmentsByPatientName(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaseById(arg0: bigint): Promise<Case> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseById(arg0);
                return from_candid_Case_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseById(arg0);
            return from_candid_Case_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaseByMRN(arg0: string): Promise<Case> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaseByMRN(arg0);
                return from_candid_Case_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaseByMRN(arg0);
            return from_candid_Case_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCases(): Promise<Array<Case>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCases();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCases();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasksForAppointment(arg0: bigint): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForAppointment(arg0);
            return result;
        }
    }
    async getTasksForCase(arg0: bigint): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasksForCase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasksForCase(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async toggleAppointmentTaskComplete(arg0: bigint, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleAppointmentTaskComplete(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleAppointmentTaskComplete(arg0, arg1, arg2);
            return result;
        }
    }
    async toggleTaskComplete(arg0: bigint, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleTaskComplete(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleTaskComplete(arg0, arg1, arg2);
            return result;
        }
    }
    async updateAppointment(arg0: bigint, arg1: string, arg2: string, arg3: Species, arg4: Sex, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string, arg10: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointment(arg0, arg1, arg2, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg3), to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, arg10);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointment(arg0, arg1, arg2, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg3), to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg4), arg5, arg6, arg7, arg8, arg9, arg10);
            return result;
        }
    }
    async updateCase(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Species, arg6: string, arg7: Sex, arg8: string, arg9: string, arg10: string, arg11: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCase(arg0, arg1, arg2, arg3, arg4, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCase(arg0, arg1, arg2, arg3, arg4, to_candid_Species_n3(this._uploadFile, this._downloadFile, arg5), arg6, to_candid_Sex_n5(this._uploadFile, this._downloadFile, arg7), arg8, arg9, arg10, arg11);
            return result;
        }
    }
}
function from_candid_Appointment_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Case_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Case): Case {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Sex_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Sex): Sex {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Species_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Species): Species {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mrn: string;
    sex: _Sex;
    tasks: _Task;
    arrivalDate: string;
    presentingComplaint: string;
    dateOfBirth: string;
    petName: string;
    appointments: Array<bigint>;
    notes: string;
    ownerLastName: string;
    breed: string;
    caseId: bigint;
    species: _Species;
}): {
    mrn: string;
    sex: Sex;
    tasks: Task;
    arrivalDate: string;
    presentingComplaint: string;
    dateOfBirth: string;
    petName: string;
    appointments: Array<bigint>;
    notes: string;
    ownerLastName: string;
    breed: string;
    caseId: bigint;
    species: Species;
} {
    return {
        mrn: value.mrn,
        sex: from_candid_Sex_n9(_uploadFile, _downloadFile, value.sex),
        tasks: value.tasks,
        arrivalDate: value.arrivalDate,
        presentingComplaint: value.presentingComplaint,
        dateOfBirth: value.dateOfBirth,
        petName: value.petName,
        appointments: value.appointments,
        notes: value.notes,
        ownerLastName: value.ownerLastName,
        breed: value.breed,
        caseId: value.caseId,
        species: from_candid_Species_n12(_uploadFile, _downloadFile, value.species)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mrn: string;
    sex: _Sex;
    tasks: _Task;
    ownerName: string;
    arrivalDate: string;
    dateOfBirth: string;
    patientName: string;
    breed: string;
    caseId: [] | [bigint];
    species: _Species;
    appointmentId: bigint;
    reason: string;
}): {
    mrn: string;
    sex: Sex;
    tasks: Task;
    ownerName: string;
    arrivalDate: string;
    dateOfBirth: string;
    patientName: string;
    breed: string;
    caseId?: bigint;
    species: Species;
    appointmentId: bigint;
    reason: string;
} {
    return {
        mrn: value.mrn,
        sex: from_candid_Sex_n9(_uploadFile, _downloadFile, value.sex),
        tasks: value.tasks,
        ownerName: value.ownerName,
        arrivalDate: value.arrivalDate,
        dateOfBirth: value.dateOfBirth,
        patientName: value.patientName,
        breed: value.breed,
        caseId: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.caseId)),
        species: from_candid_Species_n12(_uploadFile, _downloadFile, value.species),
        appointmentId: value.appointmentId,
        reason: value.reason
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    female: null;
} | {
    male: null;
} | {
    femaleSpayed: null;
} | {
    maleNeutered: null;
}): Sex {
    return "female" in value ? Sex.female : "male" in value ? Sex.male : "femaleSpayed" in value ? Sex.femaleSpayed : "maleNeutered" in value ? Sex.maleNeutered : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    feline: null;
} | {
    canine: null;
}): Species {
    return "other" in value ? Species.other : "feline" in value ? Species.feline : "canine" in value ? Species.canine : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Case>): Array<Case> {
    return value.map((x)=>from_candid_Case_n18(_uploadFile, _downloadFile, x));
}
function to_candid_Sex_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sex): _Sex {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_Species_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Species): _Species {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Species): {
    other: null;
} | {
    feline: null;
} | {
    canine: null;
} {
    return value == Species.other ? {
        other: null
    } : value == Species.feline ? {
        feline: null
    } : value == Species.canine ? {
        canine: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Sex): {
    female: null;
} | {
    male: null;
} | {
    femaleSpayed: null;
} | {
    maleNeutered: null;
} {
    return value == Sex.female ? {
        female: null
    } : value == Sex.male ? {
        male: null
    } : value == Sex.femaleSpayed ? {
        femaleSpayed: null
    } : value == Sex.maleNeutered ? {
        maleNeutered: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
